### ISSUE TITLE
How do I send to multiple recipients

### ISSUE THREAD

**Issue by cary42** [SparkPost/php-sparkpost#100]
I'm trying to figure out what the format is to send to multiple recipients using an array or object...

'recipients'=>$addresses

Does anyone know how to format $addresses for this to work properly?

**Comment by richleland** [comment]
Hi @cary42 - you can check out [this example](https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/simple_send.php#L27) - `results` is an array so you can add more than one recipient there.

I'll go ahead and close this but feel free to post follow-up questions if you have them.

**Comment by cary42** [comment]
I think my question was not well understood. I'm trying to send to more than one recipient using a variable. $results in that example is just the return value from the API...

Something like below (I put $addresses in there to show what I'm looking for). So I want two email addresses or more to be emailed using the code below.

'html' => '<p>Hello World!</p>',
        'text' => 'Hello World!',
        'subject' => 'Example Email',
        'recipients' => [
            [
                'address' =>$address
            ],
        ],

**Comment by richleland** [comment]
@cary42 as long as the variable `$address` contains an array of recipients, it should work. Can you post a larger snippet that includes (with obfuscated addresses) what the value of `$address` is?

**Comment by richleland** [comment]
BTW in that example, you've got an array (`'recipients'`) that has one object (`'address'`) that is an array of addresses, so the nesting is off. I think what you need to do is just have:

```php
'recipients' => $addresses
```

And then `$addresses` would look like this:

```php
$addresses = [
    [
        'address' => [
            'email' => 'someemail@example.com
        ]
    ],
    [
        'address' => [
            'email' => 'anotheremail@example.com
        ]
    ]
]
```

**Comment by cary42** [comment]
Ah, the above did the trick for me! Thanks.
