### ISSUE TITLE
APIResource.php doesn't account for 401 responses?

### ISSUE THREAD

**Issue by jfgrissom** [SparkPost/php-sparkpost#103]
Hi,

I'm working with this and have been troubleshooting an error message that simply states, "Received bad response from Transmission."

Once I tracked it down I see I'm getting a 401 and it isn't covered.

I wanted to put this in here, just in case someone wants to handle it. If nobody does I'll for this and create a pull request after I'm done with my  other project.

**Comment by richleland** [comment]
We now make the errors bubble up in 2.0: https://packagist.org/packages/sparkpost/sparkpost
