### ISSUE TITLE
Mail delivery seems to be hit or miss!

### ISSUE THREAD

**Issue by wastedige** [SparkPost/php-sparkpost#104]
Hi,

I'm seeing some weird issues with mail delivery. Some of the email simply do not get delivered - I set a few emails with the exact same content and sender, and some of them got delivered and some not. The mail server on the receiving side is Office365.

Each sent email does appear in Sparkpost message reports - all are successful with no rejection or bounce reports. We suspect that our emails are being flagged as spam. I'm posting a report from mail-tester.com: 
https://www.mail-tester.com/web-v2GE3r

I've attached the code I'm using:

>       $mailarray = array();
>       $mailarray['html'] = $message;
>       $mailarray['from'] = 'Inquiry <no-reply@mydomain.com>';
>       $mailarray['text'] = '';
>       $mailarray['subject'] = $subject;
>       $mailarray['replyTo'] = $clientEmail;
>       $mailarray['recipients'] = [
>         [
>           'address'=>[
>             'name'=>'xyz mail',
>             'email'=>'myname@mydomain.com'
>           ]
>         ]
>       ];
>       if(!empty($_FILES['attachment']['name'])) {
>         $mailarray['attachments'] = [
>           [
>             'type'=>'application/pdf',
>             'name'=>$_FILES['attachment']['name'],
>             'data'=>base64_encode( file_get_contents($_FILES['attachment']['tmp_name']) )
>           ]
>         ];
>       }
> 
> 
>       try {
>         $results = $sparky->transmission->send($mailarray);
>       } catch (\Exception $err) {
>         echo 'Whoops! Something went wrong';
>         var_dump($err);        
>       }

**Comment by richleland** [comment]
HI @wastedige - the best way to get support for deliverability is through our official support channel at https://support.sparkpost.com/customer/portal/emails/new. I'm going to go ahead and close this as it doesn't really relate directly to the PHP library, but deliverability issues.
