### ISSUE TITLE
Mitigate client-side timeouts

### ISSUE THREAD

**Issue by orval** [SparkPost/php-sparkpost#107]
There have been a few instances of folks asking about timeout errors. This is one example error:

> Unable to contact Transmissions API: An error occurred when fetching the URI "https://api.sparkpost.com/api/v1/transmissions/" with the adapter "guzzle6" ("cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received

Our examples do something like this:
```
$httpAdapter = new Guzzle6HttpAdapter(new Client());
```

The default timeout on the client-side appears to be 10 seconds. When under heavy load that may not be long enough. Perhaps we can change the examples to do something like this:
```
$httpAdapter = new Guzzle6HttpAdapter(new Client(['timeout' => 30000]));
```

**Comment by richleland** [comment]
Fixed with #111.
