### ISSUE TITLE
Problems parsing request as json 

### ISSUE THREAD

**Issue by cary42** [SparkPost/php-sparkpost#108]
I'm receiving this error when sending some of my emails:

`SparkPost\APIResponseException Object ( [apiMessage:protected] => invalid data format/type [apiCode:protected] => 1300 [apiDescription:protected] => Problems parsing request as json [message:protected] => Received bad response from Transmissions Problems parsing request as json [string:Exception:private] => [code:protected] => 422 [file:protected] => /home/vendor/sparkpost/php-sparkpost/lib/SparkPost/APIResource.php [line:protected] => 201 [trace:Exception:private] => Array ( [0] => Array ( [file] => /home/vendor/sparkpost/php-sparkpost/lib/SparkPost/APIResource.php [line] => 93 [function] => callResource [class] => SparkPost\APIResource [type] => -> [args] => Array ( [0] => post [1] => [2] => Array ( [body] => Array (.......`

The call that creates this error is done via loading a page in a web browser and using php 5.6

Any idea what this means or how to fix it?

**Comment by cary42** [comment]
I believe this might have been fixed with the latest version of the API

**Comment by richleland** [comment]
@cary42 thanks for reporting - please let us know if you have any further issues.
