### ISSUE TITLE
Unable to contact transmissions API

### ISSUE THREAD

**Issue by cary42** [SparkPost/php-sparkpost#109]
I often receive this error and the email does not get delivered. 

`SparkPost\APIResponseException Object ( [apiMessage:protected] => [apiCode:protected] => 0 [apiDescription:protected] => [message:protected] => Unable to contact Transmissions API: An error occurred when fetching the URI "https://api.sparkpost.com/api/v1/transmissions/" with the adapter "guzzle6" ("cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)")`

Any help would be appreciated. I've recently switched from Mandrill to Sparkpost and am having tons of issues.

**Comment by fishr01** [comment]
This is the same as #106 I will see if I can chat to him, as I know he was working on patching this.

**Comment by richleland** [comment]
Fixed with #111.
