### ISSUE TITLE
POST/PUT Object Structures Should Map to API

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/php-sparkpost#11]
It is confusing for developers to use a flattened structure of their request payloads, especially when the property names vary from the API documentation on SparkPost.com/api.

Use a idiomatic structure passthrough that maps to the API docs for all first class citizens of the SparkPost API.

**Comment by beardyman** [comment]
This is already possible.  A user can submit a mapped structure like 
```php
[ 'html'=> '<html><body><p>Welcome!!!</p></body></html>' ]
```
Or they can submit the same structure the api takes:
```php
[ 
  'content'=>[
    'html'=>'<html><body><p>Welcome!!!</p></body></html>'
  ]
]
```
The mapping is meant to be a convenience so that users could easily use the functionality of the api without needing to read the api documentation but either are usable.
