### ISSUE TITLE
Problem with "emtpy" APIResponseException

### ISSUE THREAD

**Issue by heikokrebs** [SparkPost/php-sparkpost#112]
From time to time i am getting some weird APIResponseExceptions when sending Mails.
In the exception no APIMessage and no APIDescription is set and the APICode is 0.

I can't replicate this errors, but i am seeing them from time to time in my logs.
It gets even weirder: sometimes some of these mails get send and i can find them in the Sparkpost Backend, sometimes they dont show up.

Anyone with the same problems and some hints?

**Comment by jsonnull** [comment]
I'm having the same issue, were you able to track this down?

**Comment by heikokrebs** [comment]
@jsonnull no, this is happing in production and i cant replicate the error localy yet..do you?

**Comment by jsonnull** [comment]
It's just the opposite, I'm getting the empty exception in my dev environment but the same code on our production server is working fine.

**Comment by jsonnull** [comment]
I have installed dependencies locally more recently than on the server, I'm wondering if there's some upstream conflict. That's my first guess when code works one day and doesn't work the next.

**Comment by richleland** [comment]
@jsonnull, @heikokrebs are you still experiencing this intermittently?

**Comment by richleland** [comment]
I'm going to go ahead and close this - feel free to re-open if you continue to see issues.
