### ISSUE TITLE
unexpected '$httpAdapter' error when i try to send an email

### ISSUE THREAD

**Issue by pavneet9** [SparkPost/php-sparkpost#116]
`require_once ‘vendor/autoload.php’;
 
use SparkPost\SparkPost;
use Ivory\HttpAdapter\CurlHttpAdapter;
  
$httpAdapter = new CurlHttpAdapter();
$sparky = new SparkPost($httpAdapter, ’API’);

try {
    $results = $sparky->transmission->send([
        'from' => [
            'name' => 'pavneet',
            'email' => 'email',
        ],
        'recipients' => [
            [
                'address' => [
                    email=> 'email',
                ],
            ],
        ],
        'template' => 'suggest_link',
    ]);
    echo 'Congrats! You sent an email using SparkPost!';
} catch (\Exception $exception) {
    echo $exception->getAPIMessage()."\n";
    echo $exception->getAPICode()."\n";
    echo $exception->getAPIDescription()."\n";
}
?>`

I am using the following code to make a request to send an email and i have added the required request to my composer file.

But everytime i execute the file i get unexpected '$httpAdapter' on line 33 error where i try to define the adapter.

What is that i am doing wrong

**Comment by richleland** [comment]
Hi @pavneet9 - this line:

```
$sparky = new SparkPost($httpAdapter, ’API’);
```

Needs to look like this:

```
$sparky = new SparkPost($httpAdapter, ['key' => $config['YOUR API KEY']]);
```

Let me know if that helps.

**Comment by richleland** [comment]
I'm going to go ahead and close this as answered - feel free to re-open if necessary.
