### ISSUE TITLE
Error Code Consts

### ISSUE THREAD

**Issue by rannmann** [SparkPost/php-sparkpost#117]
Are the consts documented [here](https://support.sparkpost.com/customer/en/portal/articles/2140916-extended-error-codes) available anywhere in the repo?  If not, is there any reason not to include them?

**Comment by richleland** [comment]
@rannmann the error code, message, and description are returned with the [APIResponseException](https://github.com/SparkPost/php-sparkpost/blob/master/lib/SparkPost/APIResponseException.php). Check out [this example](https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/simple_send.php#L36) for how to extract these. Does that help or are you asking for something more?

**Comment by richleland** [comment]
I'm going to go ahead and close this as answered - feel free to re-open if necessary.
