### ISSUE TITLE
CURLE_OPERATION_TIMEDOUT (28)

### ISSUE THREAD

**Issue by DrySs** [SparkPost/php-sparkpost#118]
PHP SDK returns us following Exception at random way many times on each day:

Message: Unable to contact Transmissions API: An error occurred when fetching the URI "https://api.sparkpost.com/api/v1/transmissions/" with the adapter "guzzle5" ("cURL error 28: See http://curl.haxx.se/libcurl/c/libcurl-errors.html").
API Message:
API Code: 0
API Description:

Error 28 in CURL is following:
CURLE_OPERATION_TIMEDOUT (28)
Operation timeout. The specified time-out period was reached according to the conditions.

We've already put timeout time to 0 (unlimited).

What should we do?

**Comment by richleland** [comment]
Hi @DrySs - are you still running into this issue? There are several places you can set the timeout value. The [curl_setopt docs](http://www.php.net/manual/en/function.curl-setopt.php) might be useful. Let us know if you're still running into issues here. [This SO question](http://stackoverflow.com/a/6802013) might help as well.
