### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ace411** [SparkPost/php-sparkpost#119]
Hello, 

I cannot send an email from my localhost domain 127.0.0.1. I get the following error message every time I try:

Fatal error: Uncaught SparkPost\APIResponseException: Unable to contact Transmissions API: An error occurred when fetching the URI "https://api.sparkpost.com/api/v1/transmissions/" with the adapter "guzzle6" ("cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"). in C:\xampp\htdocs\channel\vendor\sparkpost\php-sparkpost\lib\SparkPost\APIResource.php:262 Stack trace: #0 C:\xampp\htdocs\channel\vendor\sparkpost\php-sparkpost\lib\SparkPost\APIResource.php(105): SparkPost\APIResource->callResource('POST', NULL, Array) #1 C:\xampp\htdocs\channel\vendor\sparkpost\php-sparkpost\lib\SparkPost\Transmission.php(99):

**Comment by richleland** [comment]
Hi @ace411 this might be a problem with your local PHP configuration - check out [the PHP curl config docs](http://php.net/manual/en/curl.configuration.php) and [this StackOverflow answer](http://stackoverflow.com/a/34883260/174030).
