### ISSUE TITLE
Update guzzle dependency

### ISSUE THREAD

**Issue by toneplex** [SparkPost/php-sparkpost#12]
guzzlehttp/guzzle 3.x has reached end of life, so I'm wondering if there are any plans to update the dependency to a newer maintained version of guzzle. Perhaps 5.1 and above?

**Comment by richleland** [comment]
@toneplex thanks for reporting - I'm going to go ahead and test this out on a branch and see if there are any issues running tests.

**Comment by richleland** [comment]
OK did a quick check - will just require going through and updating to new syntax/classes/etc.

**Comment by toneplex** [comment]
Excellent, thanks @richleland

**Comment by richleland** [comment]
@nornholdj the latest guzzle - 6.0.1 - requires php 5.5.x. The prior guzzle version - 5.3.0 - requires php 5.4.x. Do we still need to support php 5.3.x? Do we want to go to guzzle 6 or 5? I'm assuming we would want to cut a new minor version of php-sparkpost for this update.

**Comment by nornholdj** [comment]
@richleland - I would love to, but 5.3 is still wildly popular.  According to w3techs.com (which php.net points to) V5.3 is still used by 40.5% of PHP users.  I'd be happy to refactor to use v5.4+ but thats where we were at and we refactored back to be 5.3 compatible. I don't know what is best here, mass appeal or being up-to-date.  We sided on mass appeal a few months ago.

**Comment by richleland** [comment]
@toneplex given the info from @nornholdj I'm curious - what was the driver for your original ask? Since we use guzzle under the hood is there anything about it that you, as an end-user, would gain from the upgrade to a newer version?

**Comment by richleland** [comment]
Reference link for w3techs: http://w3techs.com/technologies/details/pl-php/5/all

**Comment by toneplex** [comment]
@richleland we already have guzzle instead for the [Facebook SDK](https://packagist.org/packages/facebook/php-sdk-v4), which requires at least guzzle 4. I was hoping not to have to deal with installing multiple versions of guzzle.  

As for PHP versions, I understand PHP 5.3 is still widely used, but its EOL was [14 Aug 2014](http://php.net/eol.php).  The Facebook SDK v4 requires PHP 5.4

**Comment by richleland** [comment]
@toneplex thanks for the info. @nornholdj we should talk with the team about what versions we support. I'd prefer to be on the side of moving things forward.

**Comment by richleland** [comment]
The guzzle docs/info are a little all over the place. Collecting info here:

* Code (latest): https://github.com/guzzle/guzzle
* Docs (latest): http://guzzle.readthedocs.org/en/latest/overview.html
* Code (5.3.0): https://github.com/guzzle/guzzle/tree/5.3.0
* Docs (5.3.0): http://guzzle.readthedocs.org/en/5.3/

**Comment by bdeanindy** [comment]
From [Zend](http://www.zend.com/en/support-center/support/php-long-term-support):
```
If you are using PHP 5.3, you should know that its final release ever has been made available, marking the end of life of the PHP 5.3 series. New security vulnerabilities or critical functionality issues found in the 5.3 line will not be patched by the PHP community. How can you stay assured of long-term support for PHP 5.3 based apps and expand their usable lifetime past mid-2014?

Zend provides complete long term support and ongoing maintenance for the certified PHP runtime environment which is distributed as part of Zend Server. Support for each major PHP runtime version is provided for 5 years from initial Zend Server release on that version, extending more than 40% past than the 3 year support period provided by the open source PHP community. For instance, PHP 5.3 will continue to be supported by Zend until February 2017.
```

So the community will no longer add security or critical functionality issue patches on 5.3. That makes me lean towards 5.4+ only support for this lib.

@richleland @nornholdj @toneplex does that seem logical?

**Comment by richleland** [comment]
Sounds good to me - let's get this upgraded to support 5.4+.

**Comment by nornholdj** [comment]
@richleland++

**Comment by toneplex** [comment]
@bdeanindy sounds good to me

**Comment by bdeanindy** [comment]
I'll start work today. :)

**Comment by nornholdj** [comment]
@bdeanindy you may want to look into reverting a few commits back.  We did have it using the most recent version of Guzzle and then we decided we wanted 5.3 support (which is when we started using an old version of Guzzle).  I'm not sure if we added any new functionality since then.  Or at the very least you could use it as a reference.  It shouldn't be too many commits back.

**Comment by bdeanindy** [comment]
@nornholdj @richleland @toneplex what are your thoughts on throwing Guzzle out as a dependency and simply using cURL?

**Something along these lines as an example of a POST request**
```
$ch = curl_init();

// Uses the URL passed in that is specific to the API used
curl_setopt($ch, CURLOPT_URL, $url);	

// Sparkpost API headers expected, User-Agent being added for logging internally
curl_setopt ($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "User-Agent: " . getSDKMeta(), "Authorization: " . getApiKey());

// The content is the JSON payload that defines the request
curl_setopt ($ch, CURLOPT_POSTFIELDS, $content);

//Need to set ReturnTransfer to True in order to store the result in a variable
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

// Enable VerifyPeer and VerifyHost for SSL
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
	
$result = curl_exec($ch);
$responseObject = new stdClass(); 
$responseObject->body = $result;
$responseObject->httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

return $responseObject;
```

I plan on making this a little more generic (less POST specific) in the baseObject, but I think this gets the idea across.

My thinking around this is "if we reduce the assumptions we make on behalf of developers by reducing our dependency footprint...the SDK is more portable and standalone".

I would like your thoughts before I go down this road please. :)

**Comment by nornholdj** [comment]
@bdeanindy - We went with Guzzle to simplify that overhead.  CURL is still a dependency, it has to be installed as an extension in the php config (http://php.net/manual/en/curl.installation.php).  We went with Guzzle because it uses other methods besides curl if they're available, to help with compatibility in different environments.  From Guzzle's site: "Abstracts away the underlying HTTP transport, allowing you to write environment and transport agnostic code; i.e., no hard dependency on cURL, PHP streams, sockets, or non-blocking event loops."

**Comment by bdeanindy** [comment]
@nornholdj that helps me tremendously, I figured that would be the case...but wanted to ask.

Onwards to 5.4+ and Guzzle. :+1:

**Comment by erikroloff** [comment]
Do you guys have an ETA on updating the Guzzle dependency? 

I am currently writing a SparkPost integration and it would be great if I could use this with the new version of Guzzle. Right now I am having problems with the Guzzle versions conflicting in composer. Another package I am using requires a more current version of Guzzle and this old version of Guzzle is making it so that i can't install the SparkPost package.

**Comment by richleland** [comment]
@erikroloff great to hear you are working on an integration. @nornholdj do you think having something updated for say... this time next week is doable?

**Comment by nornholdj** [comment]
Yeah, that's doable.

**Comment by richleland** [comment]
@erikroloff will you be available later next week to install and test the branch we'll create in your setup?

**Comment by erikroloff** [comment]
After I posted this yesterday I ended up using the this package with the Guzzle update:
https://packagist.org/packages/sparkpost/php-sparkpost#dev-guzzle-update

It seems to be working totally fine with that update and I have already started on getting the integration going.  

If you guys have an update next week and it is available via composer I can try and do the updated branch, but as far as I can tell the package that I am using now seems to work.

**Comment by nornholdj** [comment]
@erikroloff - Didn't realize that branch existed.  It looks like we started working on it.  I'll make sure its up to snuff and is tested and we can get that stuff merged into the main release.

**Comment by richleland** [comment]
@nornholdj yeah that was me - I was trying to gauge the work involved for this ticket. It is definitely not tested and the existing tests fail big time.

**Comment by nornholdj** [comment]
@erikroloff I just updated the guzzle-update branch with code use the newest version of Guzzle and I submitted PR #16

**Comment by erikroloff** [comment]
I just tried out the new updated guzzle-update branch.  At least for me, this is causing problems with another package that requires guzzle 5.3.*.  It is causing composer to not be able to resolve an installable set of packages. So unfortunately Guzzle v6 is too new for my needs.  It seems like you just can't win with the versioning.

This isn't necessarily your problem, I just thought I would add my input.
