### ISSUE TITLE
I can't seem to send inline images

### ISSUE THREAD

**Issue by hydrarulz** [SparkPost/php-sparkpost#120]

**Comment by richleland** [comment]
Hi @hydrarulz - mind suppling a code snippet?

**Comment by richleland** [comment]
I added and example to [send_transmission_all_fields.php](https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/send_transmission_all_fields.php#L62) for reference.

**Comment by hydrarulz** [comment]
Thanks you

**Comment by cristoirmac** [comment]
the send_transmission_all_fields.php is no longer there, was it removed on purpose?
