### ISSUE TITLE
What happens with the daily limit 

### ISSUE THREAD

**Issue by EduardJS** [SparkPost/php-sparkpost#126]
Hello!

If I create a transmission with a recipient list which has around 30K emails, what will happen with the rest of 10K since we have only 20K daily ?

Expected behavior would be to send 20K today, 20K tomorrow and so on. What will actually happen ?

**Comment by avrahamgoldman** [comment]
At the moment any transmissions sent over the daily or monthly limit are rejected by SparkPost. See this [support article](https://support.sparkpost.com/customer/portal/articles/2030894) for more details.

**Comment by EduardJS** [comment]
Ok thank you for the reply.
What would be a good way to deal with this ?

**Comment by avrahamgoldman** [comment]
The best solution is, as stated in the support article, "consider splitting your send to accommodate the limits." Like you outlined in your question, send 20K today, 20K tomorrow and so on.

**Comment by mautematico** [comment]
Any improvements on this?
Doint this manually on the client side means
- fetching entire recipient list
- splitting recipient list
- performing multiple POST requests with _a lot_ of data that could be avoided.

It is error prone and IMO and anti pattern.

It would be absolutely cool having an option to do this split on the sparkpost side.
Considering it is currently possible to schedule messages, I think we are kind of half way on this ;)

**Comment by EduardJS** [comment]
Hei! Back in the days when I have posted this ( Can't believe It's been 7 months ), I have manages to do it on my own.

You could simply create a scheduled task and do everything in the backend after cluent is gone so he does not have to wait. Server to server POST in cURL is quite fast rather than server -> client -> sparkpost -> client results.

I have created my own small NoSQL DB based on JSON files which i am more than happy to share ( though it is not perfected to handle any errors or over limit ).

Regards!
