### ISSUE TITLE
Recipients issue

### ISSUE THREAD

**Issue by EduardJS** [SparkPost/php-sparkpost#127]
I have this very weird issue when trying to post a transmissioni using recipients from the API.

```php

$response = $sparky->request( 'GET', 'recipient-lists/test-list?show_recipients=true' )->wait();
$recipients = $response->getBody()['results']['recipients'];
echo json_encode( $recipients, JSON_PRETTY_PRINT );

$transmission = $sparky->transmissions->post([
	'campaign_id' => 'test_campaign',
	'content' => [ 'template_id' => 'templateid' ],
	'recipients' => $recipients
]);

$response = $transmission->wait();
```

```json
[
    {
        "address": {
            "email": "dulumaneduardcosmin@gmail.com",
            "name": "Eduard"
        },
        "return_path": ""
    },
    {
        "address": {
            "email": "edi@duluman.ro",
            "name": "Eduard"
        },
        "return_path": ""
    },
    {
        "address": {
            "email": "dulumana@gmail.com",
            "name": "Test"
        },
        "return_path": ""
    }
]
```

> Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.sparkpost.com/api/v1/transmissions/` resulted in a `400 Bad Request` response: { "errors": [ { "message": "At least one valid recipient is required", "code": 5002 } ] }

To note the fact that I installed this via `Composer` so everything works fine.
Weird thing is that if I try using an inline recipients list ( as in manually writing the same exact array of recipients ), it goes through perfectly.

Any ideas on this one ?

**Comment by avrahamgoldman** [comment]
Hey @EduardJS. Try the sending the same post request but use the content fields instead of the template. Let me know what happens.

**Comment by EduardJS** [comment]
@avrahamgoldman Hello!

```

Array
(
    [0] => Array
        (
            [address] => Array
                (
                    [email] => tesas@gmail.com
                    [name] => Geir
                )

            [return_path] => 
        )

    [1] => Array
        (
            [address] => Array
                (
                    [email] => edi@duluman.ro
                    [name] => Eduard
                )

            [return_path] => 
        )

    [2] => Array
        (
            [address] => Array
                (
                    [email] => yrdy@gmail.com
                    [name] => Tor
                )

            [return_path] => 
        )

    [3] => Array
        (
            [address] => Array
                (
                    [email] => dulumaneduardcosmin@gmail.com
                    [name] => Example
                )

            [return_path] => 
        )

)
<br />
<b>Fatal error</b>:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.sparkpost.com/api/v1/transmissions/` resulted in a `400 Bad Request` response:
{ &quot;errors&quot;: [ { &quot;message&quot;: &quot;At least one valid recipient is required&quot;, &quot;code&quot;: 5002 } ] }
' in /var/www/vhosts/bio365.no/email.bio365.no/lib/sparkpost/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /var/www/vhosts/bio365.no/email.bio365.no/lib/sparkpost/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/vhosts/bio365.no/email.bio365.no/lib/sparkpost/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/vhosts/bio365.no/email.bio365.no/lib/sparkpost/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/vh in <b>/var/www/vhosts/bio365.no/email.bio365.no/lib/sparkpost/lib/SparkPost/SparkPostPromise.php</b> on line <b>69</b><br />
```

I have replaced the emails here with some fake ones.

**Comment by EduardJS** [comment]
@avrahamgoldman Any news on this one ?

**Comment by avrahamgoldman** [comment]
Hi @EduardJS, sorry about the delay. It looks like the last error you got is because you passed in the recipients as a JSON encoded string - it takes an Array.
Your original problem comes from the way that the API is giving back the recipients. The API is returning each recipient with a blank `return_path`. The error
` { "errors": [ { "message": "At least one valid recipient is required", "code": 5002 } ] }` is because there is no email specified in that field. The best solution for this is to strip that value out of each of the recipients.

In between getting the recipients and the transmission, loop through each recipient and unset `return_path`.
```
for ($i = 0; $i < count($recipients); $i++) { 
	unset($recipients[$i]['return_path']);
}
```

**Comment by EduardJS** [comment]
Works fine after removing the `return_path`.

```php
foreach ( $recipients as &$recipient )
   unset( $recipient['return_path'] );
```

Took the opportunity to optimize your code a bit.

**Comment by EduardJS** [comment]
Hello! I sent 2 emails to the support, nobody replied so I thought asking here. I have successfully sent the transmission using the code above, id `84366240151899596`. At that point in time, using `GET /transmissions` would have returned the specific transmission as being submitted. Problem is that in my dashboard, I cannot see anything. The list had 24k recipients, knowing the limit is 20k daily, was the transmission "denied" ? What's the expected behaviour in this case ? I thought it would just take 20k and ignore the rest of 4 thousands.

Why would it show "submitted" if after 4 days I have nothing in my `GET /transmissions` nor in the dashboard ?

**Comment by avrahamgoldman** [comment]
Hi again @EduardJS,
The best place to ask general questions is in our [community slack](http://slack.sparkpost.com/). You can also check out this [support article](https://support.sparkpost.com/customer/en/portal/articles/2030894-daily-and-monthly-quota-limits?b_id=7411) which might answer your question.
