### ISSUE TITLE
400 Bad Request. 

### ISSUE THREAD

**Issue by rahul13695** [SparkPost/php-sparkpost#140]
Trying to send 5000 emails through backend, everything seems fine but only 4-5 emails return error code 400, where data for all 5000 emails are same. 

It was not happening till previous package php-sparkpost. after upgrading to sparkpost/sparkpost it sarted.

Need Help Quickly.

**Comment by rahul13695** [comment]
Please note the following: 
1) We were doing load testing and requests were sent 1 second apart.
2) 5000+ identical requests were sent and the vast majority succeeded, while about 4-5 failed.

Here is the response for the error cases:

400    <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>openresty/1.9.15.1</center>
</body>
</html>

**Comment by ewandennis** [comment]
@rahul13695 - Can you share the full 400 HTTP response?  The raw response body might include a more detailed error message.

To clarify, you sent 5000 identical requests - ie each with the same recipient address and message body in each case?

If you prefer, this might be easier to conduct diagnose on our [community Slack channel](sparkpost-community.slack.com).

**Comment by rahul13695** [comment]
The exact response is shared in my first reply. Please clarify if this is what you want or you were referring to something else?

Also, to answer your clarification, that is correct. Exact same email body, subject, attachment, recipient address, etc. That is to say, 5000 exactly identical requests.

**Comment by rahul13695** [comment]
Right now, I have a workaround. I'm just implementing a failure/retry (10 times) mechanism.

This seems to have solved the issue in the short term, but we would like to understand why this happened in the first place.

**Comment by ewandennis** [comment]
Thanks for posting the body.  Your retry mechanism is a good option for resilience.  If this re-occurs, please open a support ticket [using this form](https://support.sparkpost.com/customer/portal/emails/new).
