### ISSUE TITLE
No response using Async method.

### ISSUE THREAD

**Issue by calls9-filipdrabik** [SparkPost/php-sparkpost#143]
When I used one of the examples:

```
            $promise = $sparky->transmissions->post($data);
            $promise->then(
                // Success callback
                function ($result) {
                    $response = [
                        'success' => true,
                        'response' => $result,
                    ];
                    file_put_contents('_service_log-success', join(' ', $result->getBody()));
                },
                // Failure callback
                function (\Exception $e) {
                    $response = [
                        'success' => false,
                        'response' => $e->getMessage(),
                    ];
                    file_put_contents('_service_log-failed', $e->getMessage());
                }
            );
```

no response is received (also no email is send/received). When I use `$result = $promise->wait()->getBody();` everything works fine so the request it self is correct.

**Comment by Rajadas** [comment]
I've got the exact same issue.. No response when using async method, neither success nor failure.

**Comment by avrahamgoldman** [comment]
Hey @Rajadas. Because of the way async is implemented at the moment, you have to call `$promise->wait()` somewhere in the file for the script to stay alive until the request is fulfilled.

**Comment by mikhey** [comment]
This should to be added to the readme file.  I've lost nearly an hour trying to figure out why no request had been sent until I came across this.
