### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by ktdocker90** [SparkPost/php-sparkpost#144]
i got error: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by richleland** [comment]
Hi @ktdocker90 are you still experiencing this issue?

**Comment by ewandennis** [comment]
@ktdocker90 As a stopgap, you could try using [this CA cert bundle](https://github.com/kennethreitz/requests/blob/master/requests/cacert.pem).

**Comment by richleland** [comment]
I'm going to go ahead and close this out - please feel free to re-open with some additional info if this is still an issue.

**Comment by quantumwebco** [comment]
I have this issue and can't find how to fix it anywhere? Can anyone help?
