### ISSUE TITLE
Implement without using namespace

### ISSUE THREAD

**Issue by chinmay235** [SparkPost/php-sparkpost#145]
Hi, I have older php version. Using namespace not working. Please guide me how to implement sparkpost code without using namespace and alias.

Thank you
@chinmay235

**Comment by richleland** [comment]
Hi @chinmay235 we only support versions of PHP that are officially supported:
http://php.net/supported-versions.php

Namespaces were [added in 5.3](http://php.net/releases/5_3_0.php), which was EOL'd on 14 Aug 2014. We don't have any plans to remove namespaces from the library and encourage users to upgrade to at least 5.6, which is currently the oldest version we support.

**Comment by chinmay235** [comment]
Okay Thanks for reply. I have done by using external link.
