### ISSUE TITLE
SSL problem from localhost

### ISSUE THREAD

**Issue by faenryl** [SparkPost/php-sparkpost#146]
Hi,
I'm facing a problem to send email from localhost : 
` Unable to contact Transmissions API: An error occurred when fetching the URI "https://api.sparkpost.com/api/v1/transmissions/" with the adapter "guzzle6" ("cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"). `

I get the cainfo from the curl website, I tried the timeout option, but all without succcess.
Have you got a solution?
Thanks

**Comment by ewandennis** [comment]
Hi @faenryl - would you mind trying [this CA certificate bundle|https://github.com/kennethreitz/requests/blob/master/requests/cacert.pem] and reporting back?

**Comment by faenryl** [comment]
Hi @ewandennis,
It's working !! Don't know why this one works and the other don't.
Thanks.

**Comment by ewandennis** [comment]
Thanks @faenryl.  Not a universal solution but a useful stopgap at least.

**Comment by quantumwebco** [comment]
I have this problem also? How to fix?
