### ISSUE TITLE
Empty response body

### ISSUE THREAD

**Issue by RikudouSage** [SparkPost/php-sparkpost#148]
I'm trying to use your library but can't get it to work.
This is the code:
`$this->client->syncRequest("POST", "sending-domains/$this->domain/verify", [
        'dkim_verify' => TRUE,
        'spf_verify' => TRUE
      ]);`
Then I use:
`$response = $this->client->transmissions->get();`

It's sync so it returns SparkPostResponse instance, when I do `$response->getStatusCode();` it returns `200`, but when I do `$response->getBody();` I get:

`array(1) {
  ["results"]=>
  array(0) {
  }
}`

**Comment by avrahamgoldman** [comment]
@RikudouSage, looks like you want to get the response from the `syncRequest` call.
See if the following gives you what you want.
```
$response = $this->client->syncRequest("POST", "sending-domains/$this->domain/verify", [ 'dkim_verify' => TRUE, 'spf_verify' => TRUE ]);

print_r($response->getBody());
```

**Comment by richleland** [comment]
@RikudouSage I'm going to go ahead and close this out. Feel free to reopen/comment if you have any additional questions.

**Comment by kJamesy** [comment]
I have this issue too.

`		$httpClient = new GuzzleAdapter(new Client());
		$sparky = new SparkPost($httpClient, ['key' => static::getApiKey()]);
		$response = $sparky->syncRequest("GET", "sending-domains");

		print_r($response->getBody());`

I get an empty array.
And if I try to verify the domain as in your example, I get a 404 error.
I've tried different ways but it's always either a 404 or an empty array.
Any ideas?
