### ISSUE TITLE
Formatting Transactional Email

### ISSUE THREAD

**Issue by interceptclients** [SparkPost/php-sparkpost#155]
I'm using the SparkPost plugin for wordpress and find the need to format transactional emails by replacing CR/LF with `<br/>`. Would it be possible to enhance the plugin to perform this simple task or can someone provide guidance on the creation of a wordpress filter to do it?

Right now I'm modifying line 96 in mailer.http.class.php to run the php command nl2br.

Thank you ...... Rick

**Comment by avrahamgoldman** [comment]
Hey @interceptclients! I would suggest opening an issue in our [wordpress plugin repo](https://github.com/SparkPost/wordpress-sparkpost) to get some eyes on this.

**Comment by interceptclients** [comment]
Thank you, SparkPost support suggested posting here. 


Rick Barron
Chief Rain Dancer
513-201-7891
Schedule a Meeting with Me [http://schedulerick.com/]
On 10/26/2016 1:48:13 PM, Avi Goldman <notifications@github.com> wrote:
Closed #155 [https://github.com/SparkPost/php-sparkpost/issues/155].

**Comment by avrahamgoldman** [comment]
Sorry about the confusion.
