### ISSUE TITLE
Error install and use demos in Ubuntu..

### ISSUE THREAD

**Issue by dxnydlc** [SparkPost/php-sparkpost#157]
Hi, i'm donwload files on this repo and install components whit composer but at to use i'm have this error...
[Mon Nov 14 12:34:43.990354 2016] [:error] [pid 2855] [client 190.8.137.41:51173] PHP Fatal error:  Namespace declaration statement has to be the very first statement in the script in /var/www/html/mail/php-sparkpost-master/examples/message-events/get_message_events.php on line 3

i'm not apply change's in code.

Please help us

Thanks

**Comment by richleland** [comment]
Hi @dxnydlc can you try to install the library using composer instead of downloading and let us know if you have the same issue?

**Comment by richleland** [comment]
Hi @dxnydlc I'm going to go ahead and close this out. Feel free to re-open if you continue to experience issues.

**Comment by dxnydlc** [comment]
Danke!

Dany De la Cruz.



2016-12-02 9:20 GMT-05:00 Richard Leland <notifications@github.com>:
