### ISSUE TITLE
How to set options for track_clicks, track_opens, transactional

### ISSUE THREAD

**Issue by lefffen1** [SparkPost/php-sparkpost#167]
Hello! 
I have been trying for hours now to set options for track_clicks, track_opens and transactional but no matter what I try it doesn't have any effect.
Searching around it seems like at least there used to be a way to do this but I can't get it to work.

Is there a way to do this?

Thanks!

**Comment by aymg** [comment]
Hey @lefffen1! Do you know what version you are using? If you are using 2.x you should have something like this.

```php
$sparky->transmissions->post([
    'options' => [
        'open_tracking': true,
        'click_tracking': true,
    ],
    'content' => [
        'from' => [
            'name' => 'SparkPost Team',
            'email' => 'from@sparkpostbox.com',
        ],
        'subject' => 'First Mailing From PHP',
        'html' => '<html><body><h1>Congratulations, {{name}}!</h1><p>You just sent your very first mailing!</p></body></html>',
        'text' => 'Congratulations, {{name}}!! You just sent your very first mailing!',
    ],
    'substitution_data' => ['name' => 'YOUR_FIRST_NAME'],
    'recipients' => [
        [
            'address' => [
                'name' => 'YOUR_NAME',
                'email' => 'YOUR_EMAIL',
            ],
        ],
    ]
]);
?>
```

**Comment by lefffen1** [comment]
Hi aymg, thanks for getting back to me!
I am using version 2.1.0 

I thought I had tried that but apparently I hadn't. The problem was that I used the wrong names for the options, 'track_clicks' instead of 'click_tracking' and 'track_opens' for 'open_tracking'.. Don't know where I got those from. 

Thank you so much for solving this for me!

**Comment by aymg** [comment]
No problem 😄
