### ISSUE TITLE
'replyTo'

### ISSUE THREAD

**Issue by WimDC68** [SparkPost/php-sparkpost#170]
is there a possibility to add 'replyTo' ?

**Comment by avigoldman** [comment]
Hey @WimDC68 

You can set a reply to like this `'reply_to' => 'youremail@idk.com'` inside of the `content` object.

```

$promise = $sparky->transmissions->post([
    'content' => [
        'reply_to' => 'reply to me <hithere@example.com>',
        'from' => [
            'name' => 'SparkPost Team',
            'email' => 'from@sparkpostbox.com',
        ],
        'subject' => 'First Mailing From PHP',
        'html' => '<html><body><h1>Congratulations, {{name}}!</h1><p>You just sent your very first mailing!</p></body></html>',
        'text' => 'Congratulations, {{name}}! You just sent your very first mailing!',
    ],
    'substitution_data' => ['name' => 'YOUR_FIRST_NAME'],
    'recipients' => [
        [
            'address' => [
                'name' => 'YOUR_NAME',
                'email' => 'YOUR_EMAIL',
            ],
        ],
    ],
]);
```

**Comment by avigoldman** [comment]
Let me know if you any other questions!

**Comment by WimDC68** [comment]
Thank you for the wright syntax.
I’ve tried other way’s like replyTo and replyto who didn’t work

Now evrythings works fine

Kind regards
Wim De Cock


Verzonden vanuit Mail voor Windows 10

Van: Avi Goldman
Verzonden: vrijdag 11 augustus 2017 0:38
Aan: SparkPost/php-sparkpost
CC: WimDC68; Mention
Onderwerp: Re: [SparkPost/php-sparkpost] 'replyTo' (#170)

Let me know if you any other questions!
