### ISSUE TITLE
SSL problem on localhost

### ISSUE THREAD

**Issue by quantumwebco** [SparkPost/php-sparkpost#172]
On localhost I get this error

exception 'SparkPost\APIResponseException' with message 'Unable to contact Transmissions API: An error occurred when fetching the URI "https://api.sparkpost.com/api/v1/transmissions/" with the adapter "guzzle6" ("cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)").'

How to fix?

In a previous issue there was a link to a cert bundle but the link is now dead.

Thanks

**Comment by ewandennis** [comment]
@quantumwebco We previously linked to the cert bundle in the Python requests package, which has since been moved to the Certifi project. You can [download the latest bundle here](https://certifiio.readthedocs.io/en/latest/).
