### ISSUE TITLE
Undefined method SparkPost\SparkPostResponse::wait() in message events

### ISSUE THREAD

**Issue by nwehner** [SparkPost/php-sparkpost#178]
In the included examples for Message Events, e.g. https://github.com/SparkPost/php-sparkpost/blob/master/examples/message-events/get_message_events.php, line 20 refers to an undefined method.

Calling `$response = $promise->wait();` results in a PHP fatal error: "Call to undefined method SparkPost\SparkPostResponse::wait()"

Any suggestions for getting a callback?

**Comment by tuck1s** [comment]
The message events endpoint changed, and the old one is deprecated. Examples updated and tested in #201.
