### ISSUE TITLE
SPARKPOST return 401 Unauthorized

### ISSUE THREAD

**Issue by Seeryos** [SparkPost/php-sparkpost#180]
Hi everyone,

I'm trying to implement PHP method from instructions in this github to use sparkpost on my website. So I configure the tool from dashboard and all is valid. Now my function in PHP 

`
	use SparkPost\SparkPost;
	use GuzzleHttp\Client;
	use Http\Adapter\Guzzle6\Client as GuzzleAdapter;

	$httpClient = new GuzzleAdapter(new Client());
	$sparky = new SparkPost($httpClient, ['key'=>'**********']);

	$promise = $sparky->transmissions->post([
	    'content' => [
	        'from' => [
	            'name' => 'mydomain',
	            'email' => 'support@m.mydomain.fr',
	        ],
	        'subject' => 'Test',
	        'html' => '<html><body><h1>Congratulations, {{name}}!</h1><p>You just sent your very first mailing!</p></body></html>',
	        'text' => 'Congratulations, {{name}}!! You just sent your very first mailing!',
	    ],
	    'substitution_data' => ['name' => 'Yohan'],
	    'recipients' => [
	        [
	            'address' => [
	                'name' => 'Yohan',
	                'email' => '*******@gmail.com',
	            ],
	        ],
	    ]
	]);

	$sparky->setOptions(['async' => false]);
	try {
	    $response = $sparky->transmissions->get();
	    jsonKill(Success($response->getStatusCode(). " " . $response->getBody()));
	}
	catch (\Exception $e) {
		jsonKill(Error($e->getCode(). " " . $e->getMessage()));
	}
`

And the server return 

```
{
    "success": false,
    "data": "401 {\"errors\": [ {\"message\": \"Unauthorized.\"} ]}\n"
}

```
401 Message Unauthorized. I don't understand why. I contact support who tell me "Please ensure that you are using the EU API end point: https://api.eu.sparkpost.com/api/v1" 

But there is nowhere where I can put this line in my code...

for your help, THANK YOU VERY Much !

**Comment by Seeryos** [comment]
Hi, So ! I solved problem with support. So, if someone is in the same case, just open file SparkPost.php in vendor/sparkpost/sparkpost/lib/SparkPost and replace 

'host' => 'api.sparkpost.com',
by 
'host' => 'api.eu.sparkpost.com',

The problem is due to the location of my Spark account in Europe.

PROBLEM SOLVED

**Comment by tochix** [comment]
Or you could inject the host option when creating the `SparkPost`object. 

```
$httpClient = new GuzzleAdapter(new Client());
$sparky = new SparkPost($httpClient, ['key'=>'**********', 'host' => 'api.eu.sparkpost.com']);
```

That way you wouldn't need to change third party library and also remember to re-apply your change when you upgrade to a newer version of the library.

**Comment by Flucadetena** [comment]
In case anyone is having the same problem using the node library. I know this is the pho, but is the first in google results. 

The solution is to add the param "origin" with the value: "https://api.eu.sparkpost.com:443" like so:

```
	const client = new SparkPost("YOUR-API-KEY", { origin: "https://api.eu.sparkpost.com:443" });

```

as stated in the dos: https://github.com/SparkPost/node-sparkpost
