### ISSUE TITLE
Sparkpost library now requires PHP 7.1+

### ISSUE THREAD

**Issue by chriscct7** [SparkPost/php-sparkpost#182]
Due to a [sudden downstream library update](https://github.com/php-http/guzzle6-adapter/issues/56), this library now requires PHP 7.1+ (previously 5.5+).

```
  Problem 1
    - sparkpost/sparkpost dev-master requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[1.2.x-dev, dev-master].
    - sparkpost/sparkpost dev-master requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[1.2.x-dev, dev-master].
    - remove php-http/guzzle6-adapter 1.2.x-dev|keep php-http/guzzle6-adapter dev-master
    - php-http/guzzle6-adapter dev-master requires php ^7.1 -> your PHP version (7.0.31) does not satisfy that requirement.
    - Installation request for sparkpost/sparkpost dev-master -> satisfiable by sparkpost/sparkpost[dev-master].
```

Just leaving a note here since I imagine others might run into this issue and wonder what the deal is.

**Comment by chriscct7** [comment]
I'll submit a pr in a second to fix this for the project. This line:
>     "php-http/guzzle6-adapter": "^1.0",

just needs to be updated to tie to the version number of the last commit before the change.

**Comment by tuck1s** [comment]
Supported versions are now 7.2, 7.3, 7.4 and 8.0, as of #200
