### ISSUE TITLE
Update Recipient Lists API

### ISSUE THREAD

**Issue by fernandoaurelio** [SparkPost/php-sparkpost#184]
Hi, I need to update my recipient list with an email. But I can't. If anyone can help me!
here's my piece os code
`function sparkpost($method, $uri, $payload = [], $headers = [])
{
    $defaultHeaders = [ 'Content-Type: application/json' ];

    $curl = curl_init();
    $method = strtoupper($method);
    $finalHeaders = array_merge($defaultHeaders, $headers);
    $url = 'https://api.sparkpost.com:443/api/v1/'.$uri;
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, $method);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    if ($method !== 'GET') {
        curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($payload));
    }
    curl_setopt($curl, CURLOPT_HTTPHEADER, $finalHeaders);
    $result = curl_exec($curl);
    curl_close($curl);
    return $result;
}

$payloadSup = [
    'recipients' => 
    [
        [ 
            'address'=> "myemail@server.com", 
        ],
    ],       
];
$headers2 = [ 'Authorization: c7f410f468bab90648759ad6dc3e94ab8eb4e95e' ];
$email_Supress = sparkpost('PUT', 'recipient-lists/exclusion',$payloadSup,  $headers2);
$sparkExclusion = json_encode(json_decode($email_Supress, false), JSON_PRETTY_PRINT);

var_dump($sparkExclusion);
echo "Add data to Exclusion";`

Here what return's me
![capturarreturn](https://user-images.githubusercontent.com/30086062/48430921-8edfc200-e757-11e8-8440-6a436b7264e6.JPG)

**Comment by tuck1s** [comment]
This is working as designed. A recipient list is a single object. Your `total_accepted_recipients` = 1 indicates the list has been replaced with the (single) address your code provides. See https://developers.sparkpost.com/api/recipient-lists/

> The Recipient List API operates on lists as a whole and does not currently support management of individual recipients.
