### ISSUE TITLE
Composer install fails 

### ISSUE THREAD

**Issue by pedroserra** [SparkPost/php-sparkpost#186]
I successfully ran 
```
$ composer require guzzlehttp/guzzle
$ composer require php-http/guzzle6-adapter
```
as specified in the documentation, but then I run 
```
$ composer require sparkpost/sparkpost
```
and get this error:
```
Using version ^2.1 for sparkpost/sparkpost
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sparkpost/sparkpost ^2.1 -> satisfiable by sparkpost/sparkpost[2.1.0].
    - Conclusion: remove php-http/httplug v2.0.0
    - Conclusion: don't install php-http/httplug v2.0.0
    - sparkpost/sparkpost 2.1.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v1.0.0, v2.0.0].
    - Can only install one of: php-http/httplug[v1.1.0, v2.0.0].
    - Installation request for php-http/httplug (locked at v2.0.0) -> satisfiable by php-http/httplug[v2.0.0].


Installation failed, reverting ./composer.json to its original content.
```

Tried to install "php-http/httplug" but then I get 
```
  Problem 1
    - Installation request for sparkpost/sparkpost ^2.1 -> satisfiable by sparkpost/sparkpost[2.1.0].
    - sparkpost/sparkpost 2.1.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.0.0-RC1, v1.0.0-alpha, v1.0.0-alpha2, v1.0.0-alpha3, v1.0.0-beta, v1.1.0] but these conflict with your requirements or minimum-stability.
```

**Comment by andrews05** [comment]
Just had this too. PHP Http is now at version 2.0 which sparkpost doesn't support yet. Current workaround:
`composer require php-http/guzzle6-adapter "^1.1"`

**Comment by andrews05** [comment]
@SparkPost, shouldn't the guzzle6-adapter dependency be specified in the "require" section instead of "require-dev"?

**Comment by jacques** [comment]
Any chances of bumping the version of sparkpost to work on PHP 7.1+ with newer versions of the guzzle adapter?

**Comment by andrews05** [comment]
This is fixed in PR #187, if it ever gets merged.

**Comment by genyded** [comment]
This seems pretty darn important. New to Sparkpost and just spent a couple hours trying to get this up and running.

**Comment by EvanCoh** [comment]
It is important. Can you guys release a new version of sparkpost with this?

**Comment by izazael** [comment]
Slightly important. Any reason for the hold up?

**Comment by theandystratton** [comment]
Working on a new project that's heavily reliant on the client's Sparkpost usage, we need more customization than the WP plugin allows, so now I have to build things custom and prefer to use your native PHP client... getting the same error. Getting this updated is pretty critical – adding the the queue of requests for this to be updated!

**Comment by tuck1s** [comment]
This was done in #187, closing this issue.
