### ISSUE TITLE
Where to look for transmissionID

### ISSUE THREAD

**Issue by escopecz** [SparkPost/php-sparkpost#188]
[The readme states](https://github.com/SparkPost/php-sparkpost#endpoints):
```
## Endpoints
### transmissions
* **get([transmissionID] [, payload])**
    * `transmissionID` - see `uri` request options
    * `payload` - see request options
* **post(payload)**
    * `payload` - see request options
    * `payload.cc`
        * Required: No
        * Type: `Array`
        * Recipients to recieve a carbon copy of the transmission
    * `payload.bcc`
        * Required: No
        * Type: `Array`
        * Recipients to descreetly recieve a carbon copy of the transmission
* **delete(transmissionID)**
    * `transmissionID` - see `uri` request options
```
Where can I "see `uri` request options"? Why that isn't a link? If I search for "transmissionID" in the readme document it's not used elsewhere. If I try to search for it in the Sparkpost API docs I get no results. Google doesn't find anything either. Please tell me where is the list of Transmission IDs.

**Comment by tuck1s** [comment]
This section is out of date, given changes to the Transmissions endpoint: https://developers.sparkpost.com/api/transmissions/#transmissions-delete-delete-a-scheduled-transmission

I'll address this in https://github.com/SparkPost/php-sparkpost/pull/201
