### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by yepher** [SparkPost/php-sparkpost#19]
See Also: https://github.com/SparkPost/python-sparkpost/issues/51

Caveat to this issue: I maybe misreading the code and there is another way to do this that I am not seeing.

While working on the Java SDK I see this project and Python SDK require the API Key to be set inside a checked in file. [Example](https://github.com/SparkPost/python-sparkpost/blob/master/examples/transmissions/send_transmission.py#L3)

I believe things like that should not be placed inside checked in code because it is too easy to accidentally checkin you key.

I would prefer to see a name something like "config.something.example" that gets checked in. Put "config.something" would be put in the .gitignore so ti is not checked in. The example file would have the place holder properties.

The above filenames should use something appropriate for the language. In Java it would probably be "config.properties.example".

**Comment by beardyman** [comment]
I agree, this is something we have had to watch when testing and checking in code.  We definitely don't want anyone checking in their actual keys.  In this particular case (for PHP) I think it should be something specific to the examples.  I don't want to impose a config system on the user for production use.

**Comment by beardyman** [comment]
I think it would be good to generate a template of this config file as part of a post install or post update script if it doesn't exist.  That way the user doesn't need to know the format or schema of it they just need to update it. https://getcomposer.org/doc/articles/scripts.md#package-events
