### ISSUE TITLE
Reporting issue

### ISSUE THREAD

**Issue by NatalyYe** [SparkPost/php-sparkpost#192]
We see no stats for https://sunosi.com/savings and https://sunosi.com/rate-excessive-daytime-sleepiness in Sparkpost account (Summary report). The forms are working fine, notifications are being received by users. Attached are the files we are using to send out emails.
[Sunosi-mailto-files.zip](https://github.com/SparkPost/php-sparkpost/files/4002531/Sunosi-mailto-files.zip)

**Comment by tuck1s** [comment]
This code is using the library PHPMailer (over SMTP) and is unconnected with this library. Closing.
