### ISSUE TITLE
Use @example.com instead of @sample.com

### ISSUE THREAD

**Issue by yepher** [SparkPost/php-sparkpost#20]
Domains like `sample.com` and `test.com` is owned by someone. Placeholder email address examples should use `@example.com` instead.

See: 
https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/rfc822.php#L15
https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/send_transmission_all_fields.php#L21
https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/stored_template_send.php#L16

**Comment by beardyman** [comment]
@yepher - Yup, I didn't notice those before but I already implemented a change in the rework that I have in progress now (http-adapter-update branch): https://github.com/SparkPost/php-sparkpost/blob/http-adapter-update/examples/transmission/send_transmission_all_fields.php

**Comment by beardyman** [comment]
closing. fixed in #22
