### ISSUE TITLE
The specified resource does not exist

### ISSUE THREAD

**Issue by phanthinh** [SparkPost/php-sparkpost#33]
Dear!!!

I saw message "The specified resource does not exist" when use simple_send.php at source

Can you help me for this?

**Comment by beardyman** [comment]
Hi @phanthinh, 

Do you get this error for all examples?  I think I know what the issue is.  Are you trying to run the examples from within a composer install (like you installed it within a project) or is it from a cloned version of the repo?

**Comment by beardyman** [comment]
Closing due to inability to reproduce and no response.
