### ISSUE TITLE
FatalErrorException in APIResource.php

### ISSUE THREAD

**Issue by normd** [SparkPost/php-sparkpost#34]
_Submitting this for someone else, who may be able to respond to follow up questions._

After installing and running the sample code, received this error:

`FatalErrorException in APIResource.php line 196:
Call to a member function getStatusCode() on a non-object`

installed ivory http adapter :
https://github.com/egeloen/ivory-http-adapter/blob/master/doc/installation.md 
and guzzle :
http://guzzle.readthedocs.org/en/v6/overview.html#installation

but no luck

**Comment by richleland** [comment]
Some more context - user is using the code sample from the developer hub.

**Comment by mavheroe** [comment]
richleland yes. heres the codes

require 'vendor/autoload.php';

use SparkPost\SparkPost;
use GuzzleHttp\Client;
use Ivory\HttpAdapter\Guzzle6HttpAdapter;

$httpAdapter = new Guzzle6HttpAdapter(new Client());
$sparky = new SparkPost($httpAdapter, ['key'=>'YOUR API KEY']);

try {
  // Build your email and send it!
  $results = $sparky->transmission->send([
    'from'=>'From Envelope <from@sparkpostbox.com>',
    'html'=>'<html><body><h1>Congratulations, {{name}}!</h1><p>You just sent your very first mailing!</p></body></html>',
    'text'=>'Congratulations, {{name}}!! You just sent your very first mailing!',
    'substitutionData'=>['name'=>'YOUR FIRST NAME'],
    'subject'=>'First Mailing From PHP',
    'recipients'=>[
      [
        'address'=>[
          'name'=>'YOUR FULL NAME',
          'email'=>'YOUR EMAIL ADDRESS'
        ]
      ]
    ]
  ]);
  echo 'Woohoo! You just sent your first mailing!';
} catch (\Exception $err) {
  echo 'Whoops! Something went wrong';
  var_dump($err);
}

**Comment by beardyman** [comment]
Thanks for the info @mavheroe, I'm going to check this out today.

**Comment by beardyman** [comment]
@mavheroe: I'm having trouble reproducing. Can you supply your composer.json file or at least your require block?

**Comment by mavheroe** [comment]
seem to be the problem occur on local development. i tried running it on live domain, it works!
but i wonder if theres a way we could get it working on local for faster development. thanks anyway.

**Comment by beardyman** [comment]
@mavheroe: I'm glad you were able to get it to work.  I'm not sure why it would work in one environment and not the other.  We do require PHP 5.5 or greater but that should be the only thing required of the environment.  If you're able to determine the issue on local development please post an update.  Hopefully we can help someone else too.
