### ISSUE TITLE
Replace Ivory/HttpAdapter with php-httplug from php-http

### ISSUE THREAD

**Issue by beardyman** [SparkPost/php-sparkpost#36]
The Ivory/HttpAdapter has been deprecated and has been replaced by httplug by the php-http organization.  We should update it.

https://github.com/php-http/httplug

**Comment by beardyman** [comment]
Migration Guide: 
http://docs.php-http.org/en/latest/httplug/migrating.html#migrating-from-ivory-http-adapter

**Comment by Tlapi** [comment]
Hi,

any chance of updating this with code example? 

Im a bit lost right now and i dont now how to use php-sparkpost library at all.

**Comment by beardyman** [comment]
Hi @Tlapi, I'm not sure what you mean here.  We haven't implemented php-httplug yet so the library is still using the Ivory/HttpAdapter and examples can be found either in the php-sparkpost/examples/ directory or we have code snippets of workable code on the [README.md](https://github.com/SparkPost/php-sparkpost#getting-started--your-first-mailing).

**Comment by Tlapi** [comment]
Ah, ok, sorry. So this library is still using deprecated Ivory/HttpAdapter.

**Comment by beardyman** [comment]
Yup, we're working on refactoring it to use the new library but that will most likely be a little while until we can get it updated.

**Comment by nickdekruijk** [comment]
Any e.t.a.?
I hate using abandoned packages in real world projects? Probably not a high risk situation but security might be an issue.

**Comment by Nyholm** [comment]
Do you need any help introducing Httplug?

**Comment by richleland** [comment]
Handled in 2.x branch via #121 and #122.

**Comment by richleland** [comment]
2.0 has been released: https://packagist.org/packages/sparkpost/sparkpost
