### ISSUE TITLE
Wrong classname (with namespaces) in SparkPost

### ISSUE THREAD

**Issue by djagya** [SparkPost/php-sparkpost#42]
There are few wrong classes and namespaces like `Ivory\HttpAdapter` instead of `\Ivory\HttpAdapter\HttpAdapterInterface` in `SparkPost::__construct`.
It's a bit distracting, because IDE shows warnings e.g. when I'm creating a SparkPost instance with provided HttpAdapter

May I do a PR to fix these issues?

**Comment by aydrian** [comment]
Please feel free to submit a PR. That would be awesome. :)

**Comment by djagya** [comment]
Check PR #43 please.
