### ISSUE TITLE
Add 4XX errors body to exception

### ISSUE THREAD

**Issue by djagya** [SparkPost/php-sparkpost#44]
Usually errors 4XX have useful explanation about an occurred error, but the library does parse and return error body only if error code is < 400.

See `ApiResource` line 194.

I think it's better to do something like
```php
  // Handle 4XX responses, 5XX responses will throw an HttpAdapterException
if ($statusCode < 500) {
    $body = json_decode($response->getBody()->getContents(), true);
    if ($statusCode < 400) {
        return $body;
    } elseif ($statusCode === 404) {
      throw new APIResponseException('The specified resource does not exist', 404);
    } else {
        throw new APIResponseException('Received bad response from ' . ucfirst($this->endpoint) . ' API: '. $statusCode.', body:' . print_r($body));
    }
}
```

I'm ready to prepare a PR.

**Comment by kieldoyle** [comment]
+1 

Getting back a message like this:

`Received bad response from Transmissions API: 422`

Is pretty useless as the status code covers many errors as illustrated here:
https://support.sparkpost.com/customer/en/portal/articles/2140916-extended-error-codes

Sparkpost's actual response body is really useful for debugging
`{ "errors": [ { "message": "required field is missing", "description": "At least one of 'text' or 'html' needs to exist in 'content'", "code": "1400" } ] }`

**Comment by chandon** [comment]
+1

**Comment by TresErres** [comment]
@zaporylie Nice!!!

**Comment by zaporylie** [comment]
@TresErres You're welcome
