### ISSUE TITLE
Add Transmission::delete()

### ISSUE THREAD

**Issue by j4m3s** [SparkPost/php-sparkpost#46]
Please could we have `delete` on `Transmission`?  send, find and all are already there, so delete would make-up the set and allow scheduled emails to be deleted.

**Comment by richleland** [comment]
@j4m3s this method already exists - it gets inherited from the parent class. However we can add some docs for it - thanks for reporting!

**Comment by richleland** [comment]
example file available at https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/delete_transmission.php
