### ISSUE TITLE
substitutionData per recipient

### ISSUE THREAD

**Issue by woodscreative** [SparkPost/php-sparkpost#57]
Hi, it appears per recipient substitution data key is inconsistent consider the following:

<pre>$recipients = [
	[
		'name' => 'Foo',
		'email' => 'foo@example.com'
	],
	[
		'name' => 'Bar',
		'email' => 'bar@example.com'
	],
];
$mail[ 'substitutionData' ] = [
	'Company' => 'My Company Name - Works'
];
$mail 'subject' ] = 'Welcome to a Spark Post API Test';
$mail[ 'text' ] = 'Hi {{Name or 'Customer'}}, sent from {{Company}}';
$mail[ 'recipients' ] = [];
foreach ( $recipients as $recipient ) {
	$mail[ 'recipients' ][] = [
		'address' => [
		  'name'	=> $recipient[ 'name' ],
		  'email'	=> $recipient[ 'email' ]
		],
		'substitutionData' => [
			'Name' => $recipient[ 'name' ] . ' - Nope'
		],
		'substitution_data' => [
			'Name' => $recipient[ 'name' ] . '- Works'
		]	
	];
};</pre>

**Comment by richleland** [comment]
Thanks for pointing this out @woodscreative. I think this is because we don't wrap the API that far down for recipients, rather just pass those through to the API. @beardyman I wonder if there is something we could do to translate keys from title case to snake case automagically?

**Comment by symeya** [comment]
I got to the same point and can't handle this...
the array cannot have repeated keys, so how can I have this...

```
['address'=>['name'=>'Name', 'email'=>'email@gmail.com']],
['address'=>['name'=>'Name', 'email'=>'email@gmail.com']]
```

without the keys? It does not accept JSON format too..
How can I pass this recipients value?

Thanks.

**Comment by martinjbaker** [comment]
Thanks @woodscreative I was going around in circles and couldn't work out why the data wasn't coming through to the template.

**Comment by richleland** [comment]
I'm going to leave this ticket open until we have the 2.x refactor out the door. We're planning on removing the parameterMapping, which is not only confusing to a lot of people, but causes exactly these types of problems.

**Comment by suntrop** [comment]
Sorry to hook into this issue … but I am more confused than before. Does it mean it is impossible to personalize emails sent via API? 
At least I can’t get the addresses and substitutionData work together.

Currently I have my recipients …
`$address[] = array(
							'address' => array(
								'email' => "first@example.com",
								'name' => "John"
								)
						);
		$address[] = array(
							'address' => array(
								'email' => "second@example.net",
								'name' => "Mary"
								)
						);`

How do I implement the substitutionData? Do they have to be in the $address array or do they need to be an array of its own? Perhaps I missed some part of the docs, but I can't find a good example.

**Comment by suntrop** [comment]
Ok, now I got it. That was like Where's Waldo

It is not substitutionData but substitution**_d**ata

```
$address[] = array(
	'address' => array(
		'email' => 'first@example.com'
		),
	'substitution_data'=> array(
				'name'=>'John',
			)
);

$address[] = array(
	'address' => array(
		'email' => 'second@example.net'
		),
	'substitution_data'=> array(
				'name'=>'Mary',
			)
);
```

**Comment by richleland** [comment]
Handled in 2.x branch via #121 and #122.

**Comment by richleland** [comment]
2.0 has been released: https://packagist.org/packages/sparkpost/sparkpost
