### ISSUE TITLE
APIResponseException: Received bad response from Transmissions

### ISSUE THREAD

**Issue by wastedige** [SparkPost/php-sparkpost#64]
I've been stuck with this error with no luck, and looking at closed issues here did not help. This is the full error from xdebug:

```
object(SparkPost\APIResponseException)[33]
  protected 'apiMessage' => string 'Forbidden.' (length=10)
  protected 'apiCode' => int 0
  protected 'apiDescription' => string '' (length=0)
  protected 'message' => string 'Received bad response from Transmissions' (length=40)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 403
  protected 'file' => string 'C:\wamp\www\SL2\assets\vendor\sparkpost\php-sparkpost\lib\SparkPost\APIResource.php' (length=83)
  protected 'line' => int 201
```

I'm using Wampserver with PHP 5.5, I have already added cacert.pem for a previous issue regarding certificates.

Also, this is my composer.json file:
```
{
    "require": {
        "egeloen/http-adapter": "*",
        "sparkpost/php-sparkpost": "^1.0",
       "guzzlehttp/guzzle": "~6.0"
       }
}
```

**Comment by wastedige** [comment]
My bad - I had missed giving the right permissions to the API key I was using. I'm going to leave this here in case someone reaches this page due to the same mistake.

**Comment by jotapeserra** [comment]
im having same issue... what permission did you forget?

**Comment by avigoldman** [comment]
Hey @jotapeserra 👋 Make sure you have the `Transmissions: Read/Write` permission.

**Comment by jotapeserra** [comment]
thanks @avigoldman! , i already had that enabled... i was hoping there was other

**Comment by jotapeserra** [comment]
how can i handle this error? even with a try / catch the error its displayed

**Comment by dlopez-evolmind** [comment]
Hello,

I have used SparkPost before with PHP and I have had no problems, but now with a starter account (it's the only thing different) sometimes I get this error exception 'SparkPost\APIResponseException' with message 'Received bad response from Transmissions' in /www/mailing/vendor/sparkpost/php-sparkpost/lib/SparkPost/APIResource.php:244, any idea?

I have allowed all permissions

Thanks
