### ISSUE TITLE
Displaying multiple "To" recipients in a send?

### ISSUE THREAD

**Issue by mltroutt** [SparkPost/php-sparkpost#66]
I have a use case where I'm sending to multiple email addresses, as well as CCing and BCCing several more. The problem I'm running into is that everyone in the "To" list only sees their email address there, and are assuming the others who are known to supposed to be in the "To" field aren't getting the email because they don't see them there, creating mass confusion.

So, is there a way to display all the "To" recipients as you would if you were creating the email in an email client?

**Comment by richleland** [comment]
Hi @mltroutt I know you asked a while back, but yes there is a way to do this. You have to add the `header_to` field to each recipient with a comma-separated list of all recipients:

```
$results = $sparky->transmission->send([
    'from'=>'Real Rich <test@sp.richleland.com>',
    'html'=>'<p>Hello World!</p>',
    'text'=>'Hello World!',
    'subject'=>'Example Email',
    'recipients'=>[
      [
        'address'=>[
          'email'=>'rich.leland+one@sparkpost.com',
          'header_to' => 'rich.leland+one@sparkpost.com,rich.leland+two@sparkpost.com'
        ]
      ],
      [
        'address'=>[
          'email'=>'rich.leland+two@sparkpost.com',
          'header_to' => 'rich.leland+one@sparkpost.com,rich.leland+two@sparkpost.com'
        ]
      ]
    ]
  ]);
```

I'm going to go ahead and mark this resolved, but please feel free to re-open and/or ask any further questions!

**Comment by iangregory** [comment]
Is it possible to include the recipients name in the 'header_to' value? I've not had much luck with the format
`'header_to' => 'One <rich.leland+one@sparkpost.com>, Two <rich.leland+two@sparkpost.com>'`

**Comment by richleland** [comment]
Hi @iangregory yep it's possible - I just tried an example using this in the `recipients` array:

```php
        'recipients'=>[
            [
                'address'=>[
                    'email'=>'rich.leland+one@sparkpost.com',
                    'header_to' => 'Rich One <rich.leland+one@sparkpost.com>, Rich Two <rich.leland+two@sparkpost.com>'
                ]
            ],
            [
                'address'=>[
                    'email'=>'rich.leland+two@sparkpost.com',
                    'header_to' => 'Rich One <rich.leland+one@sparkpost.com>, Rich Two <rich.leland+two@sparkpost.com>'
                ]
            ]
        ]
```

Which came through successfully:

![header-to](https://cloud.githubusercontent.com/assets/34866/14984195/7b3b3f3e-110f-11e6-885d-892f177e1ef1.png)
