### ISSUE TITLE
PHP code working locally but not on Azure

### ISSUE THREAD

**Issue by wastedige** [SparkPost/php-sparkpost#68]
I have a code that looks like this:

```
use SparkPost\SparkPost; use GuzzleHttp\Client;
use Ivory\HttpAdapter\Guzzle6HttpAdapter;
$httpAdapter = new Guzzle6HttpAdapter(new Client());
$sparky = new SparkPost($httpAdapter, ['key'=>'...']);
[...]
$results = $sparky->transmission->send($mailarray);
```

It works just fine locally on WampServer, however when I deploy it to Azure it does not (PHP 5.4.45). I don't have access to Azure logs, but I managed to narrow down the problem to one line:

`$sparky = new SparkPost($httpAdapter, ['key'=>'...']);`

When I enable seeing server errors the error I'm getting on server is this: 

**Fatal error: Can't use function return value in write context in D:\home\site\wwwroot\assets\vendor\sparkpost\php-sparkpost\lib\SparkPost\SparkPost.php on line 118**

**Comment by glennflanagan** [comment]
I'm also getting this error through Wordpress in MAMP running PHP 5.4.42

**Comment by wastedige** [comment]
I found out that SparkPost requires PHP 5.5 or higher to function. Chaning the PHP version on server fixed the problem for me.

**Comment by glennflanagan** [comment]
Thanks wastedige. You were correct. I upgrade PHP to 5.6 and it runs like a dream. Thanks.
