### ISSUE TITLE
Some non-composer PHP documentation would be helpful

### ISSUE THREAD

**Issue by justinputney** [SparkPost/php-sparkpost#72]
It took me a while to even find this post and realize that I can _only_ use deprecated libraries: https://github.com/SparkPost/php-sparkpost/issues/36

Disclosure: I'm not a super-knowledgeable PHP user. However, I have decent working knowledge, and this setup feels complicated.

I was able to setup the Stripe PHP libraries (among others) with no problems—I can initialize the entire library by including one file.

Requiring Composer (or at least only have documentation for it) as well as all of these secondary libraries makes me think I might be better off with another transactional mail solution.

I'll work at it a bit longer because SparkPost has a lot of strong points, but some more documentation for people who may not be command-line coders would go a long way.

Thanks!

**Comment by oytuntez** [comment]
I should say composer is currently the industry standard to load packages in your system. However, you can still find a way to load SparkPost in your system without requiring composer (I suppose, didn't test it). Something along the lines of "autoloading packages without composer" should help with the search.

Other than that, I think they definitely need a better documentation here. The parameter names are different here than the original API documentation. I am puzzled at the moment and trying to figure things out by looking at the SDK's code.

**Comment by atwellpub** [comment]
I found this, it might be helpful: https://github.com/BrainstemStudio/sparkpostphpcurl/blob/master/sparkpost-api.php

In my case composer doesn't feel right to me either working developing WordPress plugins. I'd like to use an official noncomposer version but in the meantime it may not be too hard to use the above and API docs to develop my own.

**Comment by justinputney** [comment]
That does look helpful @atwellpub.

Fortunately, I was able to get ssh access and upgrade my server to PHP 5.6. Now I've got Composer and the Sparkpost API working.

I can imagine a lot people getting frustrated, not making this far, and giving up.

**Comment by richleland** [comment]
Thanks for the feedback @justinputney, @oytuntez and @atwellpub. We'll look into what it will take to document this/make life easier.

@oytuntez I've personally heard some mixed messages around what client libraries should do:

* In one camp there is the "I want the library to abstract away the need for me to look at the API docs, including providing convenience methods for dealing with things like attachments"
* In the other there is the "I want the library to be a really thin layer over the API docs so I can just do a 1:1 translation and understand what params to use directly in the library"

I'm curious where you fall. I'm wondering if we're just doing a bad job documenting the library and its options or if another approach altogether would work better.

**Comment by oytuntez** [comment]
You are right, these two approaches differ a lot from each other. 

- At MotaWord, when we need to publish an SDK *very quickly*, we follow "thin layer over API" path. I don't like this, however this is the easiest way to give users a usable SDK.
- Ideally in my opinion, an SDK should be completely abstract from the API and confirm to the host environment's standards. This includes models, controllers, objects etc. to abstract the actual API. This also makes it easier for SDK providers (you and us) to create backward-compatible SDKs.
- I think the problem with the current PHP SDK here is that the codebase is trying to follow both of these paths at the same time :) 
    - When you look at the code, you think nothing is abstracted and this is just a "thin layer over API" library, but then you see Transmission resource which is an abstraction over APIResource.
    - Then, Transmission object also tries to abstract input parameters, while output is not (response returned from API call directly).

These things are really **not** big deals, actually, as we can figure things out by looking at the code. My only confusion was this: "okay, so this SDK is just a request gateway to API and carries my parameters directly on the call". Then I was surprised to see the parameters were mapped differently in Transmission object. Well, once I know this, it didn't cause any other problems :)

Here are our PHP and Python SDKs, if you'd like to take a look:
- https://github.com/MotaWord/php-sdk
- https://github.com/MotaWord/python-sdk

**Comment by oytuntez** [comment]
Actually, you may want to take a look at [Apimatic](https://apimatic.io), which support Apiary and Swagger to generate client SDKs in about 10 languages.

We generated some of our SDKs from Apimatic and then customized it (the generated is not horrible, but it definitely needed some not-so-major editing). It at least builds the base structure with controllers and models, over which you can iterate quickly.

**Comment by atwellpub** [comment]
I think a SDK should be the official client method for the project in whatever languages it offers. If developers want to go fringe they should extend the SDK. 

Seems like people would want composer, node, and autoloaders, which are perfect for private servers and stuff like that.
And people in development ecosystems like me will want the same, stepless PHP include system that. 

But because there are examples out there it's not so hard to wing it. Coming from Mandrill this API is integrating very easily.

**Comment by ketseran** [comment]
In case you want to generate the SDK automatically with OpenAPI/Swagger spec, you may want to take a look at the following:

- Swagger Codegen: https://github.com/swagger-api/swagger-codegen
- AutoRest: https://github.com/Azure/autorest

**Comment by wing328** [comment]
[Swagger Codegen](https://github.com/swagger-api/swagger-codegen) is a free and open-source code generator to generate API clients (Java, C#, ObjC, Swift, Ruby, PHP, Perl, Go, NodeJS, Typescript and more) and server stubs (SpringMVC, PHP Slim, JaxRS, NodeJS and more). Recently, we've started adding auto-generated documentation (markdown) and here is an example: https://github.com/wing328/petstore-csharp

Please refer to the ["Getting Started" section](https://github.com/swagger-api/swagger-codegen#getting-started) to walk through a quick example in 5 minutes. 

If you've any question, please open a [ticket](https://github.com/swagger-api/swagger-codegen/issues) (preferred) or submit your question to [StackOverflow](http://stackoverflow.com/questions/tagged/swagger)

Disclosure: I'm a top contributor to Swagger-Codegen.

**Comment by colestrode** [comment]
It looks like this issue was opened against the 1.0 release and most of the discussion has been around how to refactor the lib. Now that we've released 2.0 as a thin wrapper and have some clear instructions on setting up with composer, I'm going to close this issue. If anyone gets tripped up with composer, please file another issue and we'll take another look at updating the docs.
