### ISSUE TITLE
Custom Headers for unwrapped endpoints missing  (not possible to work with subaccounts)

### ISSUE THREAD

**Issue by rommsen** [SparkPost/php-sparkpost#73]
Hi there,

I am building a small cli application to handle sparkpost api requests. I found this library here,  which is useful but it seems it is not possible to add custom headers to the requests when using the unwrapped endpoints feature. 

The problem is that this is mandatory to be able to work with subaccounts (X-MSYS-SUBACCOUNT header). 

Because I really need this like *now* I could provide a PR but I wanted to make sure that you are open to this addition.

**Comment by richleland** [comment]
Definitely open to it @rommsen! PR away!

**Comment by beardyman** [comment]
#82 is working to address this.  Mentioning here to link.

**Comment by richleland** [comment]
This is resolved in 2.0: https://packagist.org/packages/sparkpost/sparkpost
