### ISSUE TITLE
Unable to send a test email

### ISSUE THREAD

**Issue by CSI68** [SparkPost/php-sparkpost#74]
Hi,

I've read the default tuto to sending simple message. All seems to be correctly installed but I receive a 500 error code : 

SparkPost\APIResponseException Object
(
    [apiMessage:protected] => Could not proceed (500 error)
    [apiCode:protected] => 0
    [apiDescription:protected] => 
    [message:protected] => Received bad response from Transmissions
    [string:Exception:private] => 
    [code:protected] => 500
    [file:protected] => /var/www/html/clemweb/public_html/vendor/sparkpost/php-sparkpost/lib/SparkPost/APIResource.php
    [line:protected] => 201
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/html/clemweb/public_html/vendor/sparkpost/php-sparkpost/lib/SparkPost/APIResource.php
                    [line] => 93
                    [function] => callResource
                    [class] => SparkPost\APIResource
                    [type] => ->
                    [args] => Array
                        (
                            [0] => post
                            [1] => 
                            [2] => Array
                                (
                                    [body] => Array
                                        (
                                            [from] => From Envelope <contact@csi-internet.fr>
                                            [html] => <p>Hello World! Your name is: {{name}}</p>
                                            [text] => Hello World!
                                            [subject] => Example Email: {{name}}
                                            [recipientList] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [address] => Array
                                                                (
                                                                    [name] => ghfjhgj
                                                                    [email] => contact@csi-internet.fr
                                                                )

                                                        )

                                                )

                                        )

                                )

                        )

                )

            [1] => Array
                (
                    [file] => /var/www/html/clemweb/public_html/vendor/sparkpost/php-sparkpost/lib/SparkPost/Transmission.php
                    [line] => 92
                    [function] => create
                    [class] => SparkPost\APIResource
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [from] => From Envelope <contact@csi-internet.fr>
                                    [html] => <p>Hello World! Your name is: {{name}}</p>
                                    [text] => Hello World!
                                    [subject] => Example Email: {{name}}
                                    [recipientList] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [address] => Array
                                                        (
                                                            [name] => ghfjhgj
                                                            [email] => contact@csi-internet.fr
                                                        )

                                                )

                                        )

                                )

                        )

                )

            [2] => Array
                (
                    [file] => /var/www/html/clemweb/public_html/admin/tools.php
                    [line] => 22
                    [function] => send
                    [class] => SparkPost\Transmission
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [from] => From Envelope <contact@csi-internet.fr>
                                    [html] => <p>Hello World! Your name is: {{name}}</p>
                                    [text] => Hello World!
                                    [subject] => Example Email: {{name}}
                                    [recipientList] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [address] => Array
                                                        (
                                                            [name] => ghfjhgj
                                                            [email] => contact@csi-internet.fr
                                                        )

                                                )

                                        )

                                )

                        )

                )

            [3] => Array
                (
                    [file] => /var/www/html/clemweb/public_html/src/lib/router.class.php
                    [line] => 171
                    [args] => Array
                        (
                            [0] => /var/www/html/clemweb/public_html/admin/tools.php
                        )

                    [function] => require_once
                )

            [4] => Array
                (
                    [file] => /var/www/html/clemweb/public_html/admin/index.php
                    [line] => 7
                    [function] => route
                    [class] => router
                    [type] => ::
                    [args] => Array
                        (
                            [0] => back
                        )

                )

        )

    [previous:Exception:private] => 
)
Received bad response from Transmissions

Any ideas ?

Thanks

**Comment by bap72190** [comment]
Had the same issue, make sure the api key has "Transmissions: Read/Write" permissions. Also make sure to remove the permission "Transmissions: Read-Only". It seems it can get confused if you check both boxes for some reason.

**Comment by richleland** [comment]
Hrm, that shouldn't occur @bap72190 (the read vs. read/write causing an error) so it's possible there is an issue in this library somewhere, but we need to narrow it down.

If it's a permissions error it should surface as a 403, not a 500. Are you seeing this consistently @CSI68?

**Comment by CSI68** [comment]
I have left the code since my message, and I retry now and it works !
Very curious, I have do not change...

Thanks

**Comment by BrianLeishman** [comment]
I was also getting "Could not proceed (500 error)" with no description. Turns out in my case it was because I was setting the "From" address to "@example.com", missing the first part of the email address.

**Comment by dlopez-evolmind** [comment]
Hello,

I have used SparkPost before with PHP and I have had no problems, but now with a starter account (it's the only thing different) sometimes I get this error exception 'SparkPost\APIResponseException' with message 'Received bad response from Transmissions' in /www/mailing/vendor/sparkpost/php-sparkpost/lib/SparkPost/APIResource.php:244, any idea?

I have allowed all permissions

Thanks
