### ISSUE TITLE
Error: Can't use function return value in write context

### ISSUE THREAD

**Issue by max-mathieu** [SparkPost/php-sparkpost#75]
When configuration is missing the api key, PHP returns this weird PHP error "Can't use function return value in write context"

The issue seems to come from the use of `empty` in SparkPost.php: http://stackoverflow.com/a/2173318

**Comment by bazzmann** [comment]
We solved the fatal error removing the `trim()` function inside the `empty` one. (we are testing the library on a Drupal module).

**Comment by lfbittencourt** [comment]
You allow space-only keys removing `trim`. To keep the same validation, you can use:

```php
if (!isset($settingsConfig['key']) || !preg_match('/\S/', $settingsConfig['key'])){
```

The `/\S/` regular expression have to match any non-space character to return true.
