### ISSUE TITLE
from string doesn't works if it contains Chinese/Japanese characters

### ISSUE THREAD

**Issue by senseluo** [SparkPost/php-sparkpost#76]
when I change the from string to '美食网 <no-reply@yummy.cc>'
it will generate errors like:

 ```
 ["apiMessage":protected]=>
  string(27) "Message generation rejected"
  ["apiCode":protected]=>
  string(4) "1902"
  ["apiDescription":protected]=>
  string(38) "No Sending Domain found in From header"
  ["message":protected]=>
  string(40) "Received bad response from Transmissions"
  ["string":"Exception":private]=>
```

But that works well if I replaced '美食网' to any other english word.

Thanks~

**Comment by richleland** [comment]
Hi @senseluo if you enclose the characters in double quotes like so:

```
'from' => '"美食网" <noreply@yummy.cc>'
```

That should work. It's a known bug we need to address. Alternatively, you can use the following format as well (to avoid the ugly double-quote thing):

```
'from' => [
    'name': '美食网',
    'email': 'noreply@yummy.cc'
]
```

**Comment by richleland** [comment]
I should also mention we're going to make this automatic when we address #61.

**Comment by richleland** [comment]
I looked into making this automatic, but in the end decided not to for the following reasons:

* Our underlying API clearly has an issue that should be resolved here
* It is not guaranteed that the mailparse extension will be compiled when PHP is built so we can't just use that to solve the problem
* We'd have to write our own logic if we truly wanted to support this properly

For those reasons, we decided that updating the examples and docs for now until the underlying API is fixed would be the way to go.

Thank you so much for reporting this @senseluo.
