### ISSUE TITLE
The specified resource does not exist

### ISSUE THREAD

**Issue by RaviGotecha** [SparkPost/php-sparkpost#77]
I wont to get email opened and clicked using api in php

**Comment by richleland** [comment]
Hi @RaviGotecha you can retrieve this data using our Metrics API. We don't have a wrapper around that in this library, but you can use the `setupUnwrapped` method as shown in this example:
https://github.com/SparkPost/php-sparkpost/blob/master/examples/unwrapped/get_webhooks.php#L16

You'd of course want to use `metrics` instead and pass in the relevant options from our [API docs](https://developers.sparkpost.com/api/#/reference/metrics).

**Comment by richleland** [comment]
Closing as answered - but please feel free to create another ticket or re-open if you need more info.
