### ISSUE TITLE
The specified resource does not exist - 404 when trying to use find('transmission_id')

### ISSUE THREAD

**Issue by JamesTheCode** [SparkPost/php-sparkpost#78]
I have problem with function transmission->find('trans_id').

I'm currently testing and configuring my scripts on your API.

I can send email, it returns transmission id which I store in database and later I want to get information on this transmission so I call 'find' but it returns "The specified resource does not exist".

When I use transmission->all() it works but returns empty array.

I'm confused on how to get info on my transmission, if it was successful, opened or hard bounced.

Thx for info.

**Comment by richleland** [comment]
Hi @JamesTheCode - a little background around how our transmissions work would help. First, there are two ways to send transmissions - immediately or scheduled.

For transmissions sent immediately, we do not store the transmissions so doing a `find` on them would result in a 404. You would use our [Metrics API](https://developers.sparkpost.com/api/#/reference/metrics), [Message Events API](https://developers.sparkpost.com/api/#/reference/message-events), or [Webhooks](https://developers.sparkpost.com/api/#/reference/webhooks) to get data about your emails, depending on what you're trying to do.

For scheduled transmissions, the `find` and `all` methods will return results. As soon as those messages are sent, they will no longer show up in `find` and `all` calls.

Keep in mind that we process a ton of events, and that process is separate from sending email. Our ETLs process and store data related to your messages and only then are they available via our APIs/webhooks. That said, they don't take long to show up, but don't expect to make a call to our Transmissions API and then immediately call our other APIs for data and have results.

Does that help?

**Comment by JamesTheCode** [comment]
That helped! Thanks :)
