### ISSUE TITLE
Can't send attachment file

### ISSUE THREAD

**Issue by dhngoc** [SparkPost/php-sparkpost#84]
Hi everyone,
I'm using Transmission class to send the email. For attachment, I do like below code:

$message = array(
				"campaign_id" => "attachment_example_sparkpost_elite_only",
				"recipients" => array(
					array(
					"address" => "ngoc.dinh@edge-works.net"
					)
				),
				"content"=> array(
					"from"=> array(
						"email"=> "OurTeam@OurTeamApp.com",
						"name"=> "Example Company"
					),
					"subject"=> "Billing statement",
					"html" => "<b>Please see your attached billing statement</b>",
					"text" => 'test',
					"attachments" => array(
						array(
						"type" => "application/pdf",
						"name" => "billing.pdf",
						"data" => "Q29uZ3JhdHVsYXRpb25zLCB5b3UgY2FuIGJhc2U2NCBkZWNvZGUh"
						)
					)
			));
            // Build your email and send it!
			Transmission::send($message);
But the result, I get the errror:
[{"message":"required field is missing","description":"No valid fields exist in the 'content' object","code":"1400"}]

What does it means?

Please help me!

**Comment by richleland** [comment]
Hi @dhngoc - you don't need to specify the `content` array - we map things to the API - check out the example in https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/simple_send.php#L17.

**Comment by richleland** [comment]
Closing as answered - feel free to re-open or submit a new issue if you run into anything else @dhngoc.

**Comment by chinmay235** [comment]
@richleland I saw brocken URL. can you please check your last posted link.
