### ISSUE TITLE
Add support for cc/bcc

### ISSUE THREAD

**Issue by zaporylie** [SparkPost/php-sparkpost#87]
It took me a couple hours to understand how Cc and Bcc works with Transmissions. Would be nice to simplify it as you did for [python library](https://github.com/SparkPost/python-sparkpost/pull/73/files).

Proposal:
- add cc and bcc fields to transmission json.
- add cc and bcc automatically to recipient list on sdk level
- ensure customHeaders['Cc'] contains all Cc recipients

ref. https://support.sparkpost.com/customer/portal/articles/1948014-how-to-add-cc-and-bcc-to-emails

**Comment by richleland** [comment]
We're going to tackle this as a part of the 2.x refactor.

**Comment by richleland** [comment]
Will be resolved in 2.x with #122.

**Comment by richleland** [comment]
2.0 has been released: https://packagist.org/packages/sparkpost/sparkpost
