### ISSUE TITLE
More than one recipient

### ISSUE THREAD

**Issue by claudiusnascimento** [SparkPost/php-sparkpost#89]
How to configure more than one recipient?

Thanx!

**Comment by richleland** [comment]
HI @claudiusnascimento - recipients are just an array - so you need to add more than one recipient. See this file in our examples folder: https://github.com/SparkPost/php-sparkpost/blob/master/examples/transmission/simple_send.php#L22

**Comment by claudiusnascimento** [comment]
@richleland , thanks for your answer. I found this docs, but I tried several ways and failed.

Anyway, I am using SMTP instead of api.

Thanks again.
