### ISSUE TITLE
Reply_to Address in Templates

### ISSUE THREAD

**Issue by Shaun-FV** [SparkPost/php-sparkpost#93]
I'm trying to set the reply_to address for a template but the object key "reply_to" is not setting anythign & the UI doesn't even give a variable substitution option as there's not input for it.

**Comment by richleland** [comment]
Hi @Shaun-FV you can use substitution variables in your template for Reply-To, but only via API currently. This is a known limitation that we've got in the UI. You'd have to manage your template via API and set Reply-To that way. Does that help?

**Comment by richleland** [comment]
I'm going to mark this as resolved - but feel free to ask follow ups. You can also [chat with us in Slack](http://slack.sparkpost.com) if you want to.
