### ISSUE TITLE
rfc822 is broken

### ISSUE THREAD

**Issue by macfisherman** [SparkPost/php-sparkpost#94]
The example code at php-sparkpost/examples/transmission/rfc822.php results in the following error:
 Received bad response from Transmissions

Digging into the code, the actual error is:
`Array ( [errors] => Array ( [0] => Array ( [message] => template mime parsing error [description] => Unable to decode the text/plain part into UTF-8 [code] => 3020 ) ) )`

Simplify the content to just this:
`Subject: Example Email\n\nHello World`

results in the same error. Adding `\r\n` instead of `\n` results in same error.

**Comment by richleland** [comment]
Looks like the JSON that is getting transmitted is adding extra backslashes:

```
"{"return_path":"default@sparkpostmail.com","content":{"html":null,"text":null,"email_rfc822":"Content-Type: text\/plain\\r\\nFrom: Testing RFC <rfc@sp.richleland.com>\\r\\nSubject: Example Email\\n\\nHello World\\r\\n"},"use_draft_template":false,"recipients":[{"address":{"email":"rich.leland+rfc@sparkpost.com"}}]}"
```

**Comment by richleland** [comment]
I believe the solution here is to just do a replace of all occurrences of `\\r` or `\\n` in the encoded JSON with their non-double-backslashed versions.

**Comment by richleland** [comment]
And of course it was just a matter of changing single to double quotes. Fixed.
