### ISSUE TITLE
Composer file is required?

### ISSUE THREAD

**Issue by andrews05** [SparkPost/php-sparkpost#95]
I'm not using composer, I just installed all the classes manually in my project as I do for all php libraries. I found it very strange then when I got an error saying it couldn't find the 'composer.json' file. I haven't encountered this before, where a library needs to read a composer file. I can see in the code that all it's doing is getting the version number - is this really necessary? I'd rather not have to leave this random composer.json file floating around in my app just so SparkPost can know its own version number.

**Comment by richleland** [comment]
Thanks for submitting @andrews05 - this is a solid ask and we can go ahead and fix this up the next release.

**Comment by andrews05** [comment]
Thank you!

**Comment by richleland** [comment]
This is straight from the composer docs:

> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.

> Note: Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.

I also checked a few other libraries on github and indeed, none of them include version in the composer.json.

**Comment by richleland** [comment]
The fix for this has been published in 1.2.0.
