### ISSUE TITLE
ApiResource useless for some requests

### ISSUE THREAD

**Issue by theluk** [SparkPost/php-sparkpost#99]
For example

1. Template preview. You cannot use the unwrapped template apiresource, because it should be a post and `create` function does not support $resourcePath. The only workaround is setting the endpoint explicitly and then resetting it
2. All api POST and UPDATE calls that expects a query string parameter, as the ApiResources `create` and `update` functions simply omit the query string option.

**Comment by theluk** [comment]
even a custom class extending ApiResource is not possible as you declared the `callResource` as `private` ... -.-

i hoped the migration from mandrill would be a little bit more easy, but it breaks at the most basic segments...

**Comment by richleland** [comment]
The work we are doing in the 2.x branch will address this issue.

**Comment by richleland** [comment]
Handled in 2.x branch via #121 and #122.

**Comment by richleland** [comment]
2.0 has been released: https://packagist.org/packages/sparkpost/sparkpost
